src/objects/Resource__c.object
<CustomObject>
    <description>It stores the information about the resources.</description>
    <fields>
        <fullName>AUNo__c</fullName>
        <label>AUNo</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allocation__c</fullName>
        <defaultValue>100</defaultValue>
        <label>Percent Allocation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date resource is coming out</description>
        <inlineHelpText>Date resource is coming out</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Internal_Rate__c</fullName>
        <description>Rate cost to company</description>
        <inlineHelpText>Rate cost to company</inlineHelpText>
        <label>Internal Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name of resource</description>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <description>Rate the resource is hired.</description>
        <inlineHelpText>Rate the resource is hired.</inlineHelpText>
        <label>Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SOWNo__c</fullName>
        <label>SOW</label>
        <referenceTo>SOW__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the resource is starting</description>
        <inlineHelpText>Date the resource is starting</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Resource No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SOW__c.object
<CustomObject>
    <description>SOW is a Contract signed with the client</description>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Counter party signing the contract.</description>
        <inlineHelpText>Counter party signing the contract.</inlineHelpText>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>CM_SOWs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_SOW__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent SOW</label>
        <referenceTo>SOW__c</referenceTo>
        <relationshipName>CM_SOWs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>SOW</label>
    <nameField>
        <label>SOW No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOWs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SOWCloner.cls
public class SOWCloner
{

    public static void clone(SOW__c curSOW)
    {
        Resource__c[] curResources = new List<Resource__c>();
        SOW__c[] sows = [Select Start_Date__c,End_Date__c,Client__c,CreatedDate,
                        (Select Name,Name__c,Start_Date__c,End_Date__c,rate__c,AUNo__c,Internal_Rate__c,Allocation__c from Resources__r) 
                        From SOW__c where (Parent_SOW__c=: curSOW.Parent_SOW__c AND id!=:curSOW.id) OR
                        (id=:curSOW.Parent_SOW__c)
                        ORDER BY CreatedDate DESC LIMIT 1];
        System.debug('parent sow found'+sows.size());
        if(sows.size()==0)
        {
            return;
        }
        SOW__c parentSOW = sows[0];
        Resource__c[] resources = parentSOW.Resources__r;
        System.debug('resources found'+resources.size());
        for(Resource__c resource:resources)
        {
            Resource__c curResource = resource.clone();
            curResource.SOWNo__c=curSOW.id;
            curResource.SOWNo__c=curSOW.id;
            curResources.add(curResource);
        }
        insert curResources;
    }
}